Repository gcivil-nyu-org/team-2-inperson, pull requests merged in 2022-10, with the labels that each got.

#67 #3 and #26 UML added
  docs/.gitignore
  docs/design/#26-Admin-as-Superuser.png
  docs/design/#26-Admin-as-Superuser.txt
  docs/design/#3-View-Personalized-Recommendations-of-High-Schools.png
  docs/design/#3-View-Personalized-Recommendations-of-High-Schools.txt
Labels: NEEDS REVIEW

#56 55 GitHub setup project source tree
  .gitignore
  demos/.gitignore
  demos/OWNERS
  deploy/.gitignore
  deploy/OWNERS
  docs/OWNERS
  docs/README.md
  monitoring/.gitignore
  monitoring/OWNERS
  postman/OWNERS
  src/.gitignore
  src/OWNERS
  src/backend/.gitignore
  src/backend/OWNERS
  src/backend/README.md
  src/backend/jobs/.gitignore
  src/backend/jobs/OWNERS
  src/backend/server/.gitignore
  src/backend/server/OWNERS
  src/backend/shortlist/.gitignore
  src/backend/shortlist/OWNERS
  src/backend/shortlist/__init__.py
  src/backend/shortlist/aws.py
  src/backend/shortlist/setup.py
  src/frontend/.gitignore
  src/frontend/OWNERS
  src/frontend/README.md
  travis/.gitignore
  travis/OWNERS
Labels: NEEDS REVIEW, AREA:GITHUB

#71 Add Shortlist Deployment Diagram
  deploy/Shortlist Deployment.png
Labels: NEEDS REVIEW, AREA: Backend

#68 UML diagram For Issues #53 #29 #7
  README.md
  docs/design/#29-Students-Parents-Categorize-High-Schools.png
  docs/design/#29-Students-Parents-Categorize-High-Schools.txt
  docs/design/#53-Parents-Recommend-High-Schools-UML.png
  docs/design/#53-Parents-Recommend-High-Schools.txt
  docs/design/#7-Students-Share-ShortLists-UML.png
  docs/design/#7-Students-Share-ShortLists.txt
Labels: NEEDS REVIEW

#73 64 GitHub add travis config to root
  .travis.yml
  README.md
Labels: NEEDS REVIEW

#77 76 GitHub prepare frontend vuejs
  src/frontend/OWNERS
  src/frontend/shortlist/.eslintrc.cjs
  src/frontend/shortlist/.gitignore
  src/frontend/shortlist/.prettierrc.json
  src/frontend/shortlist/.vscode/extensions.json
  src/frontend/shortlist/OWNERS
  src/frontend/shortlist/README.md
  src/frontend/shortlist/VUE_README.md
  src/frontend/shortlist/cypress.config.js
  src/frontend/shortlist/cypress/e2e/example.cy.js
  src/frontend/shortlist/cypress/e2e/jsconfig.json
  src/frontend/shortlist/cypress/fixtures/example.json
  src/frontend/shortlist/cypress/support/commands.js
  src/frontend/shortlist/cypress/support/e2e.js
  src/frontend/shortlist/index.html
  src/frontend/shortlist/package-lock.json
  src/frontend/shortlist/package.json
  src/frontend/shortlist/public/favicon.ico
  src/frontend/shortlist/public/logo.png
  src/frontend/shortlist/src/App.vue
  src/frontend/shortlist/src/assets/main.css
  src/frontend/shortlist/src/components/__tests__/HelloWorld.spec.js
  src/frontend/shortlist/src/components/icons/MaterialIcon.vue
  src/frontend/shortlist/src/main.js
  src/frontend/shortlist/src/router/index.js
  src/frontend/shortlist/src/views/DemoView.vue
  src/frontend/shortlist/src/views/HomeView.vue
  src/frontend/shortlist/src/views/StageView.vue
  src/frontend/shortlist/vite.config.js
Labels: AREA:UI, NEEDS REVIEW, AREA:GITHUB

#85 #81 Shortlist Design Folder
  src/design/.gitignore
  src/design/OWNERS
  src/design/README.md
  src/design/logo/fonts-colors-viewlink.md
  src/design/logo/short-list-logo-light.png
  src/design/logo/shortlist-fevicon-dark.png
  src/design/logo/shortlist-fevicon-light.png
  src/design/logo/shortlist-logo-dark.png
Labels: AREA:UI, NEEDS REVIEW

#89 Simple view
  src/frontend/shortlist/src/assets/main.css
  src/frontend/shortlist/src/components/layout/sidebar/SimButton.vue
  src/frontend/shortlist/src/components/layout/sidebar/SimLeftBar.vue
  src/frontend/shortlist/src/components/layout/sidebar/SimList.vue
  src/frontend/shortlist/src/components/layout/sidebar/SimLists.vue
  src/frontend/shortlist/src/components/layout/sidebar/SimRightBar.vue
  src/frontend/shortlist/src/components/layout/sidebar/SimpleBarView.vue
  src/frontend/shortlist/src/components/school/simple/SimCard.vue
  src/frontend/shortlist/src/components/school/simple/SimCardDemo.vue
  src/frontend/shortlist/src/image/list-pic.png
  src/frontend/shortlist/src/image/trash-can.png
  src/frontend/shortlist/src/views/StageView.vue
Labels: NEEDS REVIEW

#94 #81 Update Design PP
  src/design/.gitignore
  src/design/README.md
  src/design/Wireframes.md
  src/design/wireframe images/SetPref-comps.png
  src/design/wireframe images/SetPref.png
  src/frontend/shortlist/src/components/layout/composite/CompositeView.vue
  src/frontend/shortlist/src/components/layout/navigation/Navbar.vue
  src/frontend/shortlist/src/views/DemoView.vue
Labels: AREA:UI
